### ISSUE TITLE
Allow multiple caching strategies to be implemented

### ISSUE THREAD

**Issue by Cadienvan** [Cadienvan/key-value-cache#3]
I'd like to bring out of the basic cache class the in-memory implementation and consequently provide a mechanism for allowing multiple caching strategies to be implemented using the Strategy Pattern.

Ex. redis, memcached, etc..

**Comment by Cadienvan** [comment]
0.4.0 started to move in the right direction by bringing in a separate class the In Memory Cache mechanism

**Comment by Cadienvan** [comment]
I'm currently trying some integrations with redis, this would probably need a little refactoring.

**Comment by Cadienvan** [comment]
A branch is being worked on: https://github.com/Cadienvan/key-value-cache/tree/feat/async-implementation

**Comment by Cadienvan** [comment]
The branch is ready and working, @tonycaputome waiting for your opinion on it before merging, personally I don't like how it ended as of coding bloat..

**Comment by tonycaputome** [comment]
I am not an expert on design patterns but there's something missing in this implementation. Looking around some strategy pattern example I think we need an intermediate class.
This is just an example.
https://medium.com/@gabriel_avila/design-patterns-with-typescript-strategy-35007cbcd57a

**Comment by Cadienvan** [comment]
Closing as currently the branch exists and can be worked on independently from the issue, which doesn't interfere with the library working mechanism.
