### ISSUE TITLE
Are get and set methods thread safe?

### ISSUE THREAD

**Issue by FrancescoBonizzi** [Cadienvan/key-value-cache#5]
If I invoke those methods from a heavy parallel application, may I encounter some issues?

Thanks a lot.

**Comment by Cadienvan** [comment]
Some tests should be done, still I'm pretty sure you'll be safe as the cache instance is itself an object reference and a new map reference is built on object construction, nothing is statically related

**Comment by FrancescoBonizzi** [comment]
Thanks. I will try it in such enviroment by the end of the year, in case I'll let you know if something happens!

**Comment by Cadienvan** [comment]
Hi @FrancescoBonizzi , did you have the chance to check it out? May we close the issue and reopen it in case something happens?

**Comment by Cadienvan** [comment]
Closing, considering it solved as threads are not part of the equation here.
